#!/bin/bash

# plot the distribution of tremor detections inverted by hypoinverse
# with the time offsets generated by hf/lf detection

R="-124/-123.1/48.2/48.8"
J="M10c"
datadir="/home/data2/chaosong/Seisbasics/hypoinverse/forsummary"
fam="002"
winhf="4"

#winlf="24"
#winlf="12"  # several choices
winlf="20"
#winlf="16"
lofflf="2"
ccminlf="0.5"
staloc="staloc.txt"
evtloc="eventloc.${fam}.hf.alldays.count.${winhf}_${winlf}.${lofflf}.${ccminlf}"
PS="${fam}.hflf.alldays.${winhf}_${winlf}.${lofflf}.${ccminlf}.ps"

cd $datadir

gmtset ANNOT_FONT_SIZE 12p 
gmtset PLOT_DEGREE_FORMAT ddd:mm:ssF    
gmtset BASEMAP_TYPE plain     
gmtset TICK_PEN 1p        
gmtset FRAME_PEN 1p

# start of PS script
psxy -J$J -R$R -T -Y16c -K -P > $PS

### subfig for HF
# plot frame
psbasemap -J$J -R$R -Ba0.4f0.1/a0.2f0.1WSen -K -O >> $PS

# plot coast
#pscoast -J$J -R$R -Df  -W0.5p,0/0/0,solid -L-123.2/48.3/48.3/2+lkm -G255/239/213 -S176/226/255 -K -O >> $PS
pscoast -J$J -R$R -Df  -W1p,0/0/0,solid -L-123.5/48.3/48.3/2+lkm --ANNOT_FONT_SIZE=12p -K -O >> $PS

# plot slab
slab1='/home/data2/chaosong/Seisbasics/hypoinverse/chaonew/slab1.0.grid'
cat $slab1 | awk '{print -$1,$2,-$3}' | xyz2grd -Gslab1.0.grd -I0.01/0.01 -R$R
grdcontour slab1.0.grd -J$J -R$R -C5 -A5+s10p -GL-124/48.5/-123.1/48.8 -O -K >> $PS

# plot stations
awk '{printf "%.6f %.6f \n", $3, $2}' $datadir/$staloc | psxy -J$J -R$R -St0.4 -Ggray -W0.2p/0/0/0 -K -O >> $PS

# plot 3-sta trio, in order PGC-SSIB-SILB
psxy -J$J -R$R -St0.4 -Gred -W0.2p/0/0/0 -K -O >> $PS <<EOF
-123.4508 48.65
-123.2815 48.602
-123.3875 48.7558
EOF

# plot station names
awk '{print $3, $2+0.02, "10", "0", "0", "CM", $1}' $datadir/$staloc | pstext -J$J -R$R -Gblack -K -O >> $PS

# make cpt file for detections
makecpt -CGMT_hot.cpt -I -T0/20/1 -Z > counts.cpt

# plot detections
awk '{printf "%.6f %.6f %.1f \n", $1, $2, $8}' $datadir/$evtloc | psxy -J$J -R$R -Sc0.07 -Ccounts.cpt -K -O >> $PS

# plot color scale bar
psscale -D8c/1.5c/2c/0.4c --ANNOT_FONT_PRIMARY=Helvetica --ANNOT_FONT_SIZE_PRIMARY=10p --LABEL_FONT_SIZE=12P -Ba10f5g5/:"Count of hits": -Ccounts.cpt -K -O >> $PS

### test location resolution
#echo "scale=6; -123 + 32.08 / 60, 48 + 26.79 / 60" | bc | psxy -J$J -R$R -Sc0.1 -Gblue -K -O >> $PS
#echo -123 -32.08 48 26.79 | awk '{ printf "%.6f %.6f \n", $1 + $2 / 60, $3 + $4 / 60 }' | psxy -J$J -R$R -Sc0.05 -Gblue -K -O >> $PS
#echo -123 -32.08 48 26.80 | awk '{ printf "%.6f %.6f \n", $1 + $2 / 60, $3 + $4 / 60 }' | psxy -J$J -R$R -Sc0.05 -Gblue -K -O >> $PS
#echo -123 -32.07 48 26.80 | awk '{ printf "%.6f %.6f \n", $1 + $2 / 60, $3 + $4 / 60 }' | psxy -J$J -R$R -Sc0.05 -Gblue -K -O >> $PS
#echo -123 -32.07 48 26.79 | awk '{ printf "%.6f %.6f \n", $1 + $2 / 60, $3 + $4 / 60 }' | psxy -J$J -R$R -Sc0.05 -Gblue -K -O >> $PS

# plot LFE family location
#echo -123.589 48.4218 | psxy -J$J -R$R -Sc0.1 -Gblack -K -O >> $PS

# plot lines between LFE fam and 3 sta trio
#psxy -J$J -R$R -W1.5p,black,dashed -K -O >> $PS << EOF
#-123.589 48.4218
#-123.4508 48.65
#EOF

#psxy -J$J -R$R -W1p,black,dashed -K -O >> $PS << EOF
#-123.589 48.4218
#-123.3875 48.7558
#EOF

#psxy -J$J -R$R -W0.5p,black,dashed -K -O >> $PS << EOF
#-123.589 48.4218
#-123.2815 48.602
#EOF


### subfig for LF
evtloc="eventloc.${fam}.lf.alldays.count.${winhf}_${winlf}.${lofflf}.${ccminlf}"

# plot frame
psbasemap -J$J -R$R -Ba0.4f0.1/a0.2f0.1WSen -K -Y-12c -O >> $PS

# plot coast
#pscoast -J$J -R$R -Df  -W0.5p,0/0/0,solid -L-123.2/48.3/48.3/2+lkm -G255/239/213 -S176/226/255 -K -O >> $PS
pscoast -J$J -R$R -Df  -W1p,0/0/0,solid -L-123.5/48.3/48.3/2+lkm --ANNOT_FONT_SIZE=12p -K -O >> $PS

# plot slab
grdcontour slab1.0.grd -J$J -R$R -C5 -A5+s10p -GL-124/48.5/-123.1/48.8 -O -K >> $PS
rm slab1.0.grd

# plot stations
awk '{printf "%.6f %.6f \n", $3, $2}' $datadir/$staloc | psxy -J$J -R$R -St0.4 -Ggray -W0.2p/0/0/0  -K -O >> $PS

# plot 3-sta trio, in order PGC-SSIB-SILB
psxy -J$J -R$R -St0.4 -Gred -W0.2p/0/0/0 -K -O >> $PS <<EOF
-123.4508 48.65
-123.2815 48.602
-123.3875 48.7558
EOF

# plot station names
awk '{print $3, $2+0.02, "10", "0", "0", "CM", $1}' $datadir/$staloc | pstext -J$J -R$R -Gblack  -K -O >> $PS

# plot detections
awk '{printf "%.6f %.6f %.1f \n", $1, $2, $8}' $datadir/$evtloc | psxy -J$J -R$R -Sc0.14 -Ccounts.cpt -K -O >> $PS

# plot color scale bar
psscale -D8c/1.5c/2c/0.4c --ANNOT_FONT_PRIMARY=Helvetica --ANNOT_FONT_SIZE_PRIMARY=10p --LABEL_FONT_SIZE=12P -Ba10f5g5/:"Count of hits": -Ccounts.cpt -K -O >> $PS



# end of PS script
psxy -J$J -R$R -T -O >> $PS

# delete conf. file
rm .gmt*

# convert format
ps2pdf $PS
ps2raster -Te $PS
