#!/bin/bash

# plot the distribution of tremor detections inverted by hypoinverse
# with the time offsets generated by hf/lf detection

R="-124/-123.1/48.2/48.8"
J="M10c"
datadir="/home/data2/chaosong/Seisbasics/hypoinverse/forsummary"
figdir="/home/data2/chaosong/CurrentResearch/Song_Rubin_2020/Figures"
shelldir="/home/data2/chaosong/CurrentResearch/Song_Rubin_2020/pltshell"
fam="002"
winhf="4"

#winlf="24"
#winlf="12"  # several choices
winlf="20"
#winlf="16"
lofflf="2"
ccminlf="0.5"
permsta="permstaloc.txt"
polasta="polastaloc.txt"
evtloc="eventloc.${fam}.hf.alldays.count.${winhf}_${winlf}.${lofflf}.${ccminlf}"
PS="sta_distribution.ps"

cd $datadir

gmtset ANNOT_FONT_SIZE 12p 
gmtset PLOT_DEGREE_FORMAT ddd:mm:ssF    
gmtset BASEMAP_TYPE fancy     
gmtset TICK_PEN 1p        
gmtset FRAME_PEN 1p
gmtset FRAME_WIDTH 0.15c
gmtset TICK_LENGTH 0.15c

# start of PS script
psxy -J$J -R$R -T -Y16c -K -P > $figdir/$PS

### subfig for HF
# plot frame
psbasemap -J$J -R$R -Ba0.4f0.2/a0.2f0.1WSen -K -O >> $figdir/$PS

# plot coast
#pscoast -J$J -R$R -Df  -W0.5p,0/0/0,solid -L-123.4/48.3/48.3/5+lkm -Ggray -S176/226/255 --ANNOT_FONT_SIZE=12p -K -O >> $PS
pscoast -J$J -R$R -Df  -W0.5p,0/0/0,solid -L-123.9/48.75/48.5/5+lkm+jtop -G250/249/235 -S236/244/245 --ANNOT_FONT_SIZE=10p -K -O >> $figdir/$PS

# plot slab
slab1='/home/data2/chaosong/Seisbasics/hypoinverse/chaonew/slab1.0.grid'
cat $slab1 | awk '{print -$1,$2,-$3}' | xyz2grd -Gslab1.0.grd -I0.01/0.01 -R$R
grdcontour slab1.0.grd -J$J -R$R -C5 -A5+k95/95/95+s10p -Wa1.5p,95/95/95 -GL-123.7/48.2/-123.1/48.8 -O -K >> $figdir/$PS

# plot stations, permanent triangle, polaris rectangle, filled white
awk '{printf "%.6f %.6f \n", $3, $2}' $datadir/$permsta | psxy -J$J -R$R -St0.35 -Gwhite -W0.2p/0/0/0 -K -O >> $figdir/$PS
awk '{printf "%.6f %.6f \n", $3, $2}' $datadir/$polasta | psxy -J$J -R$R -Ss0.35 -Gwhite -W0.2p/0/0/0 -K     -O >> $figdir/$PS

# plot pgc trio, in order PGC-SSIB-SILB, filled red
psxy -J$J -R$R -St0.35 -Gred -W0.2p/0/0/0 -K -O >> $figdir/$PS <<EOF
-123.4508 48.65
EOF
psxy -J$J -R$R -Ss0.35 -Gred -W0.2p/0/0/0 -K -O >> $figdir/$PS <<EOF
-123.2815 48.602
-123.3875 48.7558
EOF

# plot lzb trio, filled black
psxy -J$J -R$R -St0.35 -Gblack -W0.2p/0/0/0 -K -O >> $figdir/$PS <<EOF
-123.8236 48.6117
EOF
psxy -J$J -R$R -Ss0.35 -Gblack -W0.2p/0/0/0 -K -O >> $figdir/$PS <<EOF
-123.7332 48.6449
-123.6808 48.6317
EOF

# plot station names
awk '{print $3, $2+0.025, "10", "0", "0", "CM", $1}' $datadir/$permsta | pstext -J$J -R$R -Gblack -K -O >> $figdir/$PS
awk '{print $3, $2+0.025, "10", "0", "0", "CM", $1}' $datadir/$polasta | pstext -J$J -R$R -Gblack -K -O >> $figdir/$PS

# plot LFE family location
# NOW, i am using the locations from hypoinverse, rather than Bostock's catalog!!
psxy -J$J -R$R -Sc0.25 -Gblue -K -O >> $figdir/$PS << EOF
-123.492667 48.451500
-123.772167 48.493000
-123.863167 48.528167
-123.603333 48.440167
-123.800167 48.408833
-123.893333 48.536500
-123.864500 48.498667
-123.753333 48.525667
-123.703667 48.502667
-123.814333 48.538667
-123.838500 48.544833
-123.908000 48.494167
-123.879667 48.446167
EOF

pstext -J$J -R$R -Gblack -K -O >> $figdir/$PS << EOF
-123.492667 48.461500 10 0 0 CB 002
-123.772167 48.468000 10 0 0 CB 043
-123.893167 48.508167 10 0 0 CB 141
-123.603333 48.450167 10 0 0 CB 047
-123.800167 48.418833 10 0 0 CB 010
-123.913333 48.546500 10 0 0 CB 144
-123.864500 48.473667 10 0 0 CB 099
-123.733333 48.535667 10 0 0 CB 068
-123.693667 48.512667 10 0 0 CB 125
-123.794333 48.548667 10 0 0 CB 147
-123.848500 48.554833 10 0 0 CB 017
-123.928000 48.469167 10 0 0 CB 006
-123.879667 48.421167 10 0 0 CB 001
EOF


# the following are the lfe locations from Bostock's catalog, not used anymore!!
#psxy -J$J -R$R -Sc0.25 -Gblue -K -O >> $figdir/$PS << EOF
#-123.589000000000   48.4218000000000
#-123.793000000000   48.4600000000000
#-123.895000000000   48.5015000000000
#-123.655000000000   48.4257000000000
#-123.786000000000   48.3273000000000
#-123.929000000000   48.5300000000000
#-123.891000000000   48.4620000000000
#-123.789000000000   48.5445000000000
#-123.728000000000   48.4912000000000
#-123.838000000000   48.5285000000000
#-123.867000000000   48.5318000000000
#EOF

#pstext -J$J -R$R -Gblack -K -O >> $figdir/$PS << EOF
#-123.589000000000   48.4318000000000 10 0 0 CB 002
#-123.793000000000   48.4700000000000 10 0 0 CB 043
#-123.895000000000   48.5115000000000 10 0 0 CB 141
#-123.655000000000   48.4357000000000 10 0 0 CB 047
#-123.786000000000   48.3373000000000 10 0 0 CB 010
#-123.949000000000   48.5400000000000 10 0 0 CB 144
#-123.891000000000   48.4720000000000 10 0 0 CB 099
#-123.769000000000   48.5545000000000 10 0 0 CB 068
#-123.728000000000   48.5012000000000 10 0 0 CB 125
#-123.833000000000   48.5385000000000 10 0 0 CB 147
#-123.878000000000   48.5418000000000 10 0 0 CB 017
#EOF

# plot lines between LFE fam and 3 sta trio
#psxy -J$J -R$R -W1.5p,black,dashed -K -O >> $PS << EOF
#-123.589 48.4218
#-123.4508 48.65
#EOF

#psxy -J$J -R$R -W1p,black,dashed -K -O >> $PS << EOF
#-123.589 48.4218
#-123.3875 48.7558
#EOF

#psxy -J$J -R$R -W0.5p,black,dashed -K -O >> $PS << EOF
#-123.589 48.4218
#-123.2815 48.602
#EOF


### plot a inset large map

Rg="-128/-121/46.5/50"     # range of larger region
Jg="M4c"       # projection of larger region

#plot coast and frame for large map
psbasemap -R$Rg -J$Jg -B0 -K -O -X5.9c -Y0.1c --BASEMAP_TYPE=plain --FRAME_PEN=2.5p --TICK_PEN=2.5p --TICK_LENGTH=2.5p >> $figdir/$PS 

pscoast -R$Rg -J$Jg -Di -Gwhite -Swhite -G250/249/235 -S236/244/245 -W -A2000 -K -O  >> $figdir/$PS

awk '{print $1,$2}' $shelldir/PB2002_boundaries.gmt | psxy -J$Jg -R$Rg -Sf0.7c/0.12crt -G79/79/79 -W2p,79/79/79,solid -m -K -O  >> $figdir/$PS

echo -125.5 49.3 7 0 1 LB North America Plate | pstext -J$Jg -R$Rg -G0/0/0 -Wwhite,o,white -K -O >> $figdir/$PS
echo -127.9 47.5 7 0 1 LB Juan | pstext -J$Jg -R$Rg -G0/0/0 -Wwhite,o,white -K -O >> $figdir/$PS
echo -127.9 47.15 7 0 1 LB de Fuca | pstext -J$Jg -R$Rg -G0/0/0 -Wwhite,o,white -K -O >> $figdir/$PS
echo -127.9 46.8 7 0 1 LB Plate | pstext -J$Jg -R$Rg -G0/0/0 -Wwhite,o,white -K -O >> $figdir/$PS


psxy -R$Rg -J$Jg -W1.5p,blue -K -O -L >> $figdir/$PS << EOF
-124 48.2
-123.1 48.2
-123.1 48.8
-124 48.8
-124 48.2
EOF

# end of PS script
psxy -J$J -R$R -T -O >> $figdir/$PS

# delete conf. file
rm .gmt*

# convert format
cd $figdir
ps2pdf $PS
#ps2raster -Te $PS
ps2eps -f $PS -l

